### ISSUE TITLE
Different result

### ISSUE THREAD

**Issue by SiqiMa7** [dkaslovsky/GraphRole#12]
Hello Dan,
When I run the example.py in GraphRole, I get a different result when extracting features. Do you have any idea about the reason? Here is my result. Thanks for helping.
![Figure_1](https://github.com/dkaslovsky/GraphRole/assets/138838150/03460139-e9fd-4519-9f99-9ba223b91681)
Ma

**Comment by dkaslovsky** [comment]
Hi Ma, thanks for opening this issue and for using GraphRole! I'll have to investigate and will let you know what I find. It might be a few days before I'm able to dig into it, but it's on my radar now. Thanks again!

**Comment by SiqiMa7** [comment]
Thanks for helping. And I have another question if I want to use RoIX on other data such as DNCEmails to get non-negative matrix factorization, what part of the code should I change?

**Comment by dkaslovsky** [comment]
Hi Ma, apologies for the slow response. With respect to the different results you've reported, I am trying to determine the root cause and am wondering if this might have something to do with various dependency versions, different operating systems, python versions, or even the version of GraphRole itself. Would you be able to share as much of this information about your specific setup as possible?

In particular, any of the following might be helpful:
- Your operating system, including version
- The version of Python you are using
- The version of GraphRole you are using
- The list of dependency versions (the output of `pip list` or equivalent)
- Any other information that might be helpful that I haven't thought of!

Thanks again for reporting this. FWIW, I am able to reproduce the difference as well and am investigating.

**Comment by dkaslovsky** [comment]
Regarding your question on using GraphRole for non-negative matrix factorization, I would suggest to not use GraphRole as it isn't intended to perform such decompositions on arbitrary inputs. Instead, I'd recommend using a library such as sklearn directly. For example, GraphRole's NMF is performed using this library (`from sklearn.decomposition import NMF`). See `graphrole/roles/factor.py for details`.
