### ISSUE TITLE
Update dependencies to modern versions

### ISSUE THREAD

**Issue by rjurney** [dkaslovsky/GraphRole#13]
I updated the requirements.txt to include more modern dependencies. I was unable to work with this library in my class's docker image / Python environment until I did so.

cc @dkaslovsky

**Comment by rjurney** [comment]
Fixed in #14 Can you review?

**Comment by dkaslovsky** [comment]
Thanks @rjurney! I'll plan to get this reviewed and merged very soon (today or tomorrow). I appreciate it!

**Comment by rjurney** [comment]
Cool! Thanks

**Comment by dkaslovsky** [comment]
Thanks again, merged!

I'll get the version bumped to get a new release going here soon and will upload to pypi.

**Comment by rjurney** [comment]
Great, thanks! Btw, does this implement RolX, RefeX or something in between? Does it scale as well as RolX?

**Comment by dkaslovsky** [comment]
It implements both RolX and RefeX as described by in the papers [1] and [2]:

[1] Henderson, et al. [It’s Who You Know: Graph Mining Using Recursive Structural Features](http://www.cs.cmu.edu/~leili/pubs/henderson-kdd2011.pdf).

[2] Henderson, et al. [RolX: Structural Role Extraction & Mining in Large Graphs](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46591.pdf).

I am unsure about how the scalability compares to RolX as I have not evaluated it from this perspective (and it has been quite some time since I implemented it). It does leverage pandas functions where possible and attempts to be efficient, or at least not gratuitously inefficient, but I couldn't make an assertion as to the actual scalability or complexity.

I hope this is helpful!
