### ISSUE TITLE
Transfer from a graph to another

### ISSUE THREAD

**Issue by bokveizen** [dkaslovsky/GraphRole#15]
Hi, thank you for your wonderful repo.

In the original paper of RolX, the authors did experiments transferring the knowledge of a labeled graph to an unlabelled one.
I am wondering how I can do this using the code in GraphRole.

Thank you for your help in advance.

**Comment by dkaslovsky** [comment]
Hello, thanks for your kind words as well as your question.

It has been a long time since I dug into the details of the RolX paper(s). I believe that section 3 of [this paper](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46591.pdf) explains how transfer learning is accomplished. GraphRole can be used to both compute graph features as well as assign role classifications, essentially providing the functionalities of ReFeX and RolX. Transfer learning is accomplished using these results as demonstrated by the examples in the authors' paper(s).

I hope this is helpful and I'm happy to help further with the functionality of GraphRole, but how one applies its output (e.g., for transfer learning) might be a bit out of scope for this package.

Thanks again!

**Comment by bokveizen** [comment]
Thank you for the reply! Maybe I should contact the authors of RolX instead :D
