### ISSUE TITLE
Any specific reason to use DataFrame as the data structure?

### ISSUE THREAD

**Issue by bokveizen** [dkaslovsky/GraphRole#17]
Hi! Thank you for your work again.

I wonder whether there is any specific reason to use DataFrame as the data structure?
Would there be better choices for better efficiency?

**Comment by dkaslovsky** [comment]
Hi, thanks for your comments/questions!

DataFrames are a standard choice for performing the types of aggregations and calculations underlying GraphRole as well as representing the tabular results. Certainly there are DataFrame libraries that scale beyond Pandas and perhaps it could make sense to reimplement GraphRole using some of them, especially if there is a need for distributed computation.

However, as I understand your question, it seems you have something different in mind? What efficiency issues are you encountering and what data structure(s) were you hoping to use?

**Comment by bokveizen** [comment]
Thank you for your reply! I am considering something like [TensorDict](https://pytorch.org/tensordict/) and the possibility to use GPUs for faster computation.

**Comment by dkaslovsky** [comment]
Interesting. That would likely introduce an entirely different compute paradigm and likely necessitate a reimplementation rather than serve as a drop-in replacement. I'm going to close this issue as I don't plan on working on such a reimplementation in the foreseeable future, but certainly welcome contributions/PRs if you are so inclined! Thanks again for your interest and the suggestion. Please feel free to reopen the issue if there is more to discuss!
