### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BradKML** [dkaslovsky/GraphRole#2]
1. How is this different from official implementation? https://github.com/benedekrozemberczki/RolX
2. Can this be integrated with algorithms in https://karateclub.readthedocs.io/
3. What about the node embedders of https://github.com/metagraph-dev/metagraph/issues/207 ?

**Comment by dkaslovsky** [comment]
Thanks for your questions and for using GraphRole.  I'll attempt answering each one individually:
1. I am aware of this implementation but am not familiar enough with it (I have not used it myself) to be able to describe the differences.  The intent for GraphRole is a straightforward implementation that follows the original papers as closely as possible.  It is possible that the two implementations are similar, but it is also possible that they differ in details and/or optimizations.  It is worth noting that while the implementation you've cited is undoubtedly of high quality, it is no more an "official" implementation than GraphRole, as neither repo is from the paper's authors to my knowledge.
2. Can you be more specific as to what you mean or intend by "integrated with the algorithms?"
3. Can you please clarify your question so that I can attempt a complete answer.

In general, I made an attempt to provide thorough documentation in the repo's README, but if anything is in need of clarification I'd be very grateful for you bringing it to my attention.

Thanks again for opening this issue and for your interest in GraphRole!

**Comment by BradKML** [comment]
For 2, would you consider RolX to belong in the KarateClub node embedding library similar to the other algorithms?
- https://karateclub.readthedocs.io/en/latest/notes/resources.html#neighbourhood-based-node-embedding
- https://karateclub.readthedocs.io/en/latest/notes/resources.html#structural-node-embedding

For 3, would you consider RolX to belong in the Metagraph repos?

**Comment by dkaslovsky** [comment]
As I'm not the original author of the paper, I can only give my opinion.  It does seem that the RolX algorithm can fall under the category of structural node embedding and neighbourhood-based embeddings, so it would be reasonable to be listed together with those algorithms in any collection or repo (such as those you've cited).  Again, GraphRole was written to be a Python implementation of ReFeX/RolX, but the original algorithms were developed by authors of the paper cited in this repo's README.

I hope that is helpful!  Thanks again for. your interest.
